### ISSUE TITLE
Change the way cryptotvgen is distributed & provide precompiled binaries

### ISSUE THREAD

**Issue by shrub77** [GMUCERG/LWC#18] opened 2020-08-07 11:49 UTC
With the upcoming changes to the LWC_TB which provide automated benchmarking, cryptotvgen will be necessary for designers to generate the required test vectors. 

Right now, using cryptotvgen requires many steps to compile+install which are not guaranteed to work on all systems and requires some system knowledge to solve any issues during installation. Furthermore, the install does not even make cryptotvgen directly accessible, requiring `python3 -m cryptotvgen` instead of a direct call `cryptotvgen`, which is not obvious, as @kammoh discovered recently.

It would be better from a user perspective if we instead packaged cryptotvgen into executable cli programs (deb, rpm, exe) and provided those binaries with releases. This would not be difficult to set up and can be automated with CI/CD proposed in #16 

What are your thoughts @kammoh @Grimgoodbye

**Comment by ekawat** [comment] 2020-08-09 17:15
Weird. I was calling cryptotvgen without installing it. The only reason I can think why cryptotvgen is not automatically called is if the default path to python3 in the cryptovgen file does not exist in the system (the first line #!/bin/usr/python3). Maybe changing this default my be okay (or Kammoh's system is specific to his setup). @kammoh, can you please confirm?

I agree that it'd be good to add CI/CD and precompiled binaries by default though. 


Many improvements can also be made to cryptotvgen and prepare_src folder, but this probably should be taken up by another issue to keep this one focused on CI/CD.

**Comment by kammoh** [comment] 2020-08-09 19:32
@ekawat The hashbang in the installed binary is automatically generated by `setuptools` for the entry_point and is always correct. The problem is how the entry_point is defined, which probably _only_ works under some python versions / OS combination but is not the approach described in the [documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation). TL/DR a function named `main` (or whatever you add to `entry_point`) needs to be actually there (i.e just naming the file to `__main__.py` cannot address this). This is addressed in an upcoming PR.

I actually like the idea of an installable `cryptotvgen` script, which can easily be run by the user. I don't see a need for binary package distributions.

I'd suggest removing `prepare_src` all together and migrating it's functionality to `cryptotvgen`.

**Comment by ekawat** [comment] 2020-08-10 16:32
Thanks! The new rewrite for prepare_libs seems much better and more concise. I appreciate the removal of ugly preprocessing that we had. I didn't know any better then.

Anyway, I'm okay with the general changes but I'd like to comment on the use flow of this new version.

During development of a Cipher Core, user typically needs to rerun the software to generate a test vector to compare the result several time for debugging. During this period, the software is added with debug information.

The current code, if I understand correctly, seems to re-extract from the tar zip everytime prepare_lib is called. It also doesn't support for incremental re-compilation. We can do this as a separate changelist but I'd like to add this to a todo list if possible.


PS: you might want to deprecate --dbg from cryptotvgen as we no longer support this after this change, i.e. we don't have a debug build anymore.

**Comment by ekawat** [comment] 2020-08-10 16:33
Also, you might want to remove the text regarding --<implementation_name> since we no longer support it.

**Comment by kammoh** [comment] 2020-08-10 20:29
Thank you very much for your feedback! I was able to incorporate most of your suggestions.
Regarding re-extraction of SUPERCOP and lack of incremental recompilation: this is partly by design to ensure the user has the latest source code (in case of updates pushed in SUPERCOP) and to minimize the risk of stale reference code. The whole extract and compile process is pretty fast (33 seconds on my laptop with `-Os` optimized compilation, 18 seconds without optimization, i.e really no time compared to the RTL development or simulation times), but can also be entirely bypassed if using the `--candidates-dir` switch (can e.g. be pointed to an already extracted SUPERCOP source directory in `$HOME/.cryptotvgem`). Also I really see no need to run "--prepare_libs" during the development cycle, unless an update to the the reference code has been published.

**Comment by kammoh** [comment] 2020-08-11 02:10
I think #20 addresses most of the things here. I see no merit (and lot's of issues) with binary distribution. Closing, but please feel free to re-open or open a new issue if something is missing.

**Closed by kammoh** 2020-08-11 02:10 UTC
